### ISSUE TITLE
plot_cold_pool add variable

### ISSUE THREAD

**Issue by jcaracappa1** [NOAA-EDAB/ecodata#110]
Can we add a "variable" argument to plot_cold_pool() so that we can isolate an individual plot?

**Comment by BBeltz1** [comment]
@andybeet assigning you to this

**Comment by andybeet** [comment]
would `varName` = "cold_pool", "persistence", and "extent" work?

**Comment by jcaracappa1** [comment]
yes those options work. looks great

**Comment by andybeet** [comment]
@jcaracappa1 making a PR to pull these changes + into dev
