### ISSUE TITLE
plot_rec_hms error

### ISSUE THREAD

**Issue by jcaracappa1** [NOAA-EDAB/ecodata#122]
Getting the following error for plot_rec_hms() on dev

![image](https://github.com/NOAA-EDAB/ecodata/assets/57966543/68e650f7-3f0a-4109-9902-4dbf8ba25b8e)

**Comment by sgaichas** [comment]
good catch, this will fix it in a call but we should change the function

`plot_rec_hms(shadedRegion = NULL, report = "NewEngland")`

**Comment by sgaichas** [comment]
i think it should be fixed if this line changes from 
`plot_rec_hms <- function(shadedRegion = shadedRegion,`
to 
`plot_rec_hms <- function(shadedRegion = NULL,`
