### ISSUE TITLE
Consistent data types in data files

### ISSUE THREAD

**Issue by slarge** [NOAA-EDAB/ecodata#15]
Pedantic. It would be best to make sure columns are consistent across data files. 

```
`library(ecodata)
ecodata::chl_pp
ecodata::common_tern

str(chl_p)
str(common_tern)
```

> str(chl_pp)
'data.frame':	88076 obs. of  5 variables:
 $ Time : int  1998 1998 1998 1998 1999 1999 1999 1999 2000 2000 ...
 $ Units: Factor w/ 4 levels "mg m^-3","UNITLESS",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ Var  : chr  "ANNUAL_CHLOR_A_MEDIAN OC-CCI PAN" "ANNUAL_CHLOR_A_MEDIAN OC-CCI PAN" "ANNUAL_CHLOR_A_MEDIAN OC-CCI PAN" "ANNUAL_CHLOR_A_MEDIAN OC-CCI PAN" ...
 $ Value: num  0.558 0.474 0.504 0.463 0.756 ...
 $ EPU  : Factor w/ 4 levels "GB","GOM","MAB",..: 1 4 2 3 1 4 2 3 1 4 ...

> str(common_tern)
'data.frame':	3060 obs. of  5 variables:
 $ Var  : chr  "EER COTE Productivity" "EER COTE Productivity" "EER COTE Productivity" "EER COTE Productivity" ...
 $ Time : int  1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 ...
 $ Value: num  NA NA NA 1.62 1.51 1.42 1.26 1.55 0.47 1.66 ...
 $ EPU  : chr  "GOM" "GOM" "GOM" "GOM" ...
 $ Units: chr  "fledged chicks per nest" "fledged chicks per nest" "fledged chicks per nest" "fledged chicks per nest" ...

**Comment by kimberly-bastille** [comment]
Data have all been switched to use the same column order (Time, Var, Value, EPU, Units) and are all formatted as tibbles. 

Example of chl_pp and comdat below. 

**ecodata::chl_pp**
A tibble: 18,900 x 5
   Time   Var               Value EPU   Units          
   chr     chr                dbl    chr      chr          
 1 A_1998 ANNUAL_PPD_MEDIAN 0.462 GOM   gcarbon/m^2/day
 2 A_1998 ANNUAL_PPD_MEDIAN 0.531 GB    gcarbon/m^2/day
 
**ecodata::comdat**
A tibble: 26,744 x 5
    Time Var                   Value EPU   Units      
      int    chr                    dbl    fct      chr      
 1  1964 Planktivore Landings 40814. GOM   metric tons
 2  1964 Planktivore Landings 12722. SS    metric tons
