### ISSUE TITLE
data or figure fix for missing survey data

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/ecodata#18]
Survey data for the NEFSC fall MAB is missing in 2017 due to vessel issues.
It appears there is no 2017 point for fall (which is appropriate) but then plots draw a line from 2016 to 2018.
Should we add 2017 with NA value, or to deal with in plots separately? How is this done for other datasets?
affects:
- MAB survey biomass by feeding guild plot (MAFMC report)
- proportion of NEFMC benthivores in MAB plot (NEFMC and MAFMC reports)
- possibly other survey figs?

**Comment by slucey** [comment]
We should put in an NA so it looks like other plots (i.e., EcoMon).

Sean M. Lucey
Fisheries Biologist
Ecosystem Dynamics and Assessment Branch
U. S. Dept. of Commerce/NOAA/NMFS
Northeast Fisheries Science Center
166 Water Street, Woods Hole, MA 02543
508-495-2011 (voice)
508-495-2232 (fax)

**Comment by seanhardison1** [comment]
I've updated ecodata to include NAs for years with missing data in the aggregated and species-level survey data. The plotting code in the SOE documents have also been updated to account for the change

**Comment by sgaichas** [comment]
Did we miss MAB 2017 spring as well? I thought just one season had a complete miss but our figures show both missing.

**Comment by slucey** [comment]
We did not miss spring 2017.  The data should be there.

Sean


Sean M. Lucey
Fisheries Biologist
Ecosystem Dynamics and Assessment Branch
U. S. Dept. of Commerce/NOAA/NMFS
Northeast Fisheries Science Center
166 Water Street, Woods Hole, MA 02543
508-495-2011 (voice)
508-495-2232 (fax)

**Comment by seanhardison1** [comment]
It appears that there was a bug in the code aggregating survdat, where the number of fall tows was used to find the mean weight per tow for the spring survey. I have fixed this error and am working on updating ecodata. 

The change turns the spring benthivore trend from negative to positive, more closely resembling the NEAMAP data. There are no changes to be made in the SOE text.

**Comment by seanhardison1** [comment]
@sgaichas @slucey survey data sets are updated.

**Comment by slucey** [comment]
Was that an error in my code? Oops...thanks for catching it.

**Comment by seanhardison1** [comment]
no worries, it was a quick fix and didn't change much. Will close this now
