### ISSUE TITLE
.rbuildignore

### ISSUE THREAD

**Issue by andybeet** [NOAA-EDAB/ecodata#24]
^inst$

is there a reason this is not part of the build?
i am wondering if this might be part of the install from github issue (wih build_vignettes=T)

**Comment by seanhardison1** [comment]
I excluded inst because inst/extdata holds all of the raw files, and building the package without excluding this folder would greatly extend build time

**Comment by seanhardison1** [comment]
Update - We will move raw data to the data-raw folder. With this, we will need to change the relative paths sourcing data in processing scripts in `/data-raw`

**Comment by andybeet** [comment]
Also put all of the scripts that process this "raw_data" in the raw data folder (since they are not really part of the package either). Then output the .rda files from these processing scripts to the data folder

**Comment by seanhardison1** [comment]
This should be fixed now
