### ISSUE TITLE
consolidate dataset documentation into`R/datasets.R`

### ISSUE THREAD

**Issue by bbest** [NOAA-EDAB/ecodata#29]
For instance in [R/](https://github.com/NOAA-EDAB/ecodata/tree/ed64ae5d37bdc4b4b97f07b42a0d8f6b6dbf7c16/R), contents of the following *.R files can be pasted alphabetically into a new `datasets.R`:

* [bennet.R](https://github.com/NOAA-EDAB/ecodata/blob/ed64ae5d37bdc4b4b97f07b42a0d8f6b6dbf7c16/R/bennet.R)
* [ches_bay_wq.R](https://github.com/NOAA-EDAB/ecodata/blob/ed64ae5d37bdc4b4b97f07b42a0d8f6b6dbf7c16/R/ches_bay_wq.R)
* [aquaculture.R](https://github.com/NOAA-EDAB/ecodata/blob/ed64ae5d37bdc4b4b97f07b42a0d8f6b6dbf7c16/R/aquaculture.R)
* ...

The functions and datasets defined in [R/](https://github.com/NOAA-EDAB/ecodata/tree/master/R) can be listed under headers (like **Datasets**, **Read**, **Visualize**, etc) in the [Function reference • ecodata](https://noaa-edab.github.io/ecodata/reference/index.html). See:

- example: [Function reference • shipr](https://benioffoceaninitiative.github.io/s4wr/reference/index.html)
  * [_pkgdown.yml](https://github.com/BenioffOceanInitiative/s4wr/blob/master/inst/_pkgdown.yml)).
- [Introduction to pkgdown • pkgdown](https://pkgdown.r-lib.org/articles/pkgdown.html#reference)
  > To override the default, provide a `reference` field in `_pkgdown.yml`. The `reference` should be an array of objects containing `title`, `desc` (description), and list of `contents`. Since common prefix and suffixes are often used for functional grouping, you can use the functions `starts_with()` and `ends_with()` to automatically include all functions with a common prefix or suffix. To match more complex patterns, use `matches()` with a regular expression.

**Comment by kimberly-bastille** [comment]
https://noaa-edab.github.io/ecodata/reference/index.html
