### ISSUE TITLE
add subfolders to clean up docs

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/ecodata#30]
Probably minor, but we have a lot of loose images in docs right now. I'd suggest putting them in an image folder if we are keeping them here, or else restructuring to pull from a single images folder for many documents.

the setup block for the visualization rmds already has this line in it
```
#Image Directory
image.dir <- here::here("image")
```
so we would just import the images from there.
right now there is an additional line in each codeblock going around this; for example

```
image.dir <- here::here("docs")

knitr::include_graphics(file.path(image.dir, "MABcondition_2019.jpg"))
```

**Comment by kimberly-bastille** [comment]
created an [images](https://github.com/NOAA-EDAB/ecodata/tree/master/docs/images) under docs to clean it up
