### ISSUE TITLE
update dataset attributes to work with Uploader

### ISSUE THREAD

**Issue by bbest** [NOAA-EDAB/ecodata#38]
Hi @kimberly-bastille,

I finally revisited the awesome dataset attributes you added to work with the Uploader:

* **`data_steward`**
* **`tech-doc_url`**
* **`data_files`**

There's a minor issue of most datasets getting attributes assigned after `use_data`, so they're not included when loading the dataset from the package, eg [get_ch_bay_sal.R](https://github.com/NOAA-EDAB/ecodata/blob/cf6bed26ef385a8a1957064bcbbf7479363dbc91/data-raw/get_ch_bay_sal.R#L22-L32):

This line:

```r
 usethis::use_data(ch_bay_sal, overwrite = T)
```

Needs to happen _**after**_ the attributes get set:

```r
  attr(ch_bay_sal, "tech-doc_url") <- "https://noaa-edab.github.io/tech-doc/chesapeake-bay-salinity.html"
  attr(ch_bay_sal, "data_files")   <- list(
    ch_bay_sal_csv = ch_bay_sal_csv)
  attr(ch_bay_sal, "data_steward") <- c(
    "Charles Pellerin <charles.pellerin@noaa.gov>",
    "Bruce Vogt <bruce.vogt@noaa.gov")
```

I'll create a pull request with the dataset summaries and fixes.

**Comment by bbest** [comment]
Here's the `output: github_document` rendering of tables in [inst/get_dataset_attributes.Rmd](https://github.com/bbest/ecodata/blob/61514778575ca188026c79d9aeed5247885ecdd9/inst/get_dataset_attributes.Rmd)...

## datasets

### done

``` r
kable(datasets_done)
```

| name                            | has\_data | has\_steward | has\_doc | has\_files |
| :------------------------------ | :-------- | :----------- | :------- | :--------- |
| aggregate\_biomass              | TRUE      | TRUE         | TRUE     | TRUE       |
| ch\_bay\_sal                    | TRUE      | TRUE         | TRUE     | TRUE       |
| chl\_pp                         | TRUE      | TRUE         | TRUE     | TRUE       |
| hp\_density                     | TRUE      | TRUE         | TRUE     | TRUE       |
| phyto\_size                     | TRUE      | TRUE         | TRUE     | TRUE       |
| productivity\_anomaly           | TRUE      | TRUE         | TRUE     | TRUE       |
| seasonal\_oisst\_anom           | TRUE      | TRUE         | TRUE     | TRUE       |
| seasonal\_sst\_anomaly\_gridded | TRUE      | TRUE         | TRUE     | TRUE       |

### todo

``` r
kable(datasets_todo)
```

| name                         | has\_data | has\_steward | has\_doc | has\_files |
| :--------------------------- | :-------- | :----------- | :------- | :--------- |
| aquaculture                  | TRUE      | FALSE        | FALSE    | FALSE      |
| bennet                       | TRUE      | FALSE        | FALSE    | FALSE      |
| blue\_runner                 | TRUE      | FALSE        | FALSE    | FALSE      |
| bottom\_temp\_glorys         | TRUE      | FALSE        | FALSE    | FALSE      |
| bottom\_temp                 | TRUE      | FALSE        | FALSE    | FALSE      |
| CalanusStage                 | TRUE      | FALSE        | FALSE    | FALSE      |
| ches\_bay\_wq                | TRUE      | FALSE        | FALSE    | FALSE      |
| coast                        | TRUE      | FALSE        | FALSE    | FALSE      |
| cold\_pool\_sf               | TRUE      | FALSE        | FALSE    | FALSE      |
| cold\_pool                   | TRUE      | FALSE        | FALSE    | FALSE      |
| comdat                       | TRUE      | FALSE        | FALSE    | FALSE      |
| commercial\_div              | TRUE      | FALSE        | FALSE    | FALSE      |
| energy\_density              | TRUE      | FALSE        | FALSE    | FALSE      |
| engagement                   | TRUE      | FALSE        | FALSE    | FALSE      |
| epu\_sf                      | TRUE      | FALSE        | FALSE    | FALSE      |
| forage\_anomaly              | TRUE      | FALSE        | FALSE    | FALSE      |
| grayseal                     | TRUE      | FALSE        | FALSE    | FALSE      |
| gsi\_old                     | TRUE      | FALSE        | FALSE    | FALSE      |
| gsi                          | TRUE      | FALSE        | FALSE    | FALSE      |
| habitat\_occupancy           | TRUE      | FALSE        | FALSE    | FALSE      |
| habitat\_vulnerability       | TRUE      | FALSE        | FALSE    | FALSE      |
| harborporpoise               | TRUE      | FALSE        | FALSE    | FALSE      |
| heatwave\_anom\_gridded      | TRUE      | FALSE        | FALSE    | FALSE      |
| heatwave\_peak\_date         | TRUE      | FALSE        | FALSE    | FALSE      |
| heatwave\_year               | TRUE      | FALSE        | FALSE    | FALSE      |
| heatwave                     | TRUE      | FALSE        | FALSE    | FALSE      |
| hms\_cpue                    | TRUE      | FALSE        | FALSE    | FALSE      |
| hms\_landings                | TRUE      | FALSE        | FALSE    | FALSE      |
| ichthyo\_diversity           | TRUE      | FALSE        | FALSE    | FALSE      |
| long\_term\_sst              | TRUE      | FALSE        | FALSE    | FALSE      |
| mab\_inshore\_survey         | TRUE      | FALSE        | FALSE    | FALSE      |
| mass\_inshore\_survey        | TRUE      | FALSE        | FALSE    | FALSE      |
| nao                          | TRUE      | FALSE        | FALSE    | FALSE      |
| narw                         | TRUE      | FALSE        | FALSE    | FALSE      |
| ne\_inshore\_survey\_species | TRUE      | FALSE        | FALSE    | FALSE      |
| ne\_inshore\_survey          | TRUE      | FALSE        | FALSE    | FALSE      |
| ne\_wind                     | TRUE      | FALSE        | FALSE    | FALSE      |
| nefsc\_survey\_disaggregated | TRUE      | FALSE        | FALSE    | FALSE      |
| nefsc\_survey                | TRUE      | FALSE        | FALSE    | FALSE      |
| new\_england                 | TRUE      | FALSE        | FALSE    | FALSE      |
| observed\_sharks             | TRUE      | FALSE        | FALSE    | FALSE      |
| ppr                          | TRUE      | FALSE        | FALSE    | FALSE      |
| rec\_hms                     | TRUE      | FALSE        | FALSE    | FALSE      |
| recdat                       | TRUE      | FALSE        | FALSE    | FALSE      |
| seabird\_MAB                 | FALSE     | FALSE        | FALSE    | FALSE      |
| seabird\_ne                  | TRUE      | FALSE        | FALSE    | FALSE      |
| slopewater                   | TRUE      | FALSE        | FALSE    | FALSE      |
| species\_dist                | TRUE      | FALSE        | FALSE    | FALSE      |
| species\_groupings           | TRUE      | FALSE        | FALSE    | FALSE      |
| stock\_status                | TRUE      | FALSE        | FALSE    | FALSE      |
| stom\_fullness               | TRUE      | FALSE        | FALSE    | FALSE      |
| stratification               | TRUE      | FALSE        | FALSE    | FALSE      |
| wcr                          | TRUE      | FALSE        | FALSE    | FALSE      |
| wind\_dev\_speed             | TRUE      | FALSE        | FALSE    | FALSE      |
| wind\_occupancy              | TRUE      | FALSE        | FALSE    | FALSE      |
| wind\_revenue                | TRUE      | FALSE        | FALSE    | FALSE      |
| zoo\_abund                   | TRUE      | FALSE        | FALSE    | FALSE      |
| zoo\_diversity               | TRUE      | FALSE        | FALSE    | FALSE      |
| zoo\_oi                      | TRUE      | FALSE        | FALSE    | FALSE      |
| zoo\_sli\_anom               | TRUE      | FALSE        | FALSE    | FALSE      |
| zoo\_strat\_abun             | TRUE      | FALSE        | FALSE    | FALSE      |

## attributes

### stewards

``` r
kable(dataset_stewards)
```

| name                            | data\_steward                                  |
| :------------------------------ | :--------------------------------------------- |
| aggregate\_biomass              | Sean Lucey <sean.lucey@noaa.gov>               |
| ch\_bay\_sal                    | Charles Pellerin <charles.pellerin@noaa.gov>   |
| ch\_bay\_sal                    | Bruce Vogt \<<bruce.vogt@noaa.gov>             |
| chl\_pp                         | Kimberly Hyde <kimberly.hyde@noaa.gov>         |
| hp\_density                     | Chris Orphanides <chris.orphanides@noaa.gov>   |
| phyto\_size                     | Kimberly Hyde <kimberly.hyde@noaa.gov>         |
| productivity\_anomaly           | Kimberly Bastille <kimberly.bastille@noaa.gov> |
| seasonal\_oisst\_anom           | Kimberly Bastille <kimberly.bastille@noaa.gov> |
| seasonal\_sst\_anomaly\_gridded | Kimberly Bastille <kimberly.bastille@noaa.gov> |

### docs

``` r
kable(dataset_techdocurls)
```

| name                            | tech\_doc\_url                                                          |
| :------------------------------ | :---------------------------------------------------------------------- |
| aggregate\_biomass              | <https://noaa-edab.github.io/tech-doc/aggroups.html>                    |
| ch\_bay\_sal                    | <https://noaa-edab.github.io/tech-doc/chesapeake-bay-salinity.html>     |
| chl\_pp                         | <https://noaa-edab.github.io/tech-doc/chl-pp.html>                      |
| hp\_density                     | <https://noaa-edab.github.io/tech-doc/harbor-porpoise-bycatch.html>     |
| phyto\_size                     | <https://noaa-edab.github.io/tech-doc/chl-pp.html>                      |
| productivity\_anomaly           | <https://noaa-edab.github.io/tech-doc/fish-productivity-indicator.html> |
| seasonal\_oisst\_anom           | <https://noaa-edab.github.io/tech-doc/seasonal-sst-anomalies.html>      |
| seasonal\_sst\_anomaly\_gridded | <https://noaa-edab.github.io/tech-doc/seasonal-sst-anomalies.html>      |

### files

``` r
kable(dataset_datafiles)
```

| name                            | data\_files                                                                                     |
| :------------------------------ | :---------------------------------------------------------------------------------------------- |
| aggregate\_biomass              | Aggregate\_Survey\_biomass\_20 (5).RData                                                        |
| ch\_bay\_sal                    | SR\_Salinity.csv                                                                                |
| chl\_pp                         | 1998\_2020-OCCCI\_MODISA-CHLOR\_A-STATS\_ANOMS-NES\_EPU\_NOESTUARIES-SOE\_V2021-SOE\_FORMAT.csv |
| chl\_pp                         | 1998\_2020-OCCCI\_MODISA-PPD-STATS\_ANOMS-NES\_EPU\_NOESTUARIES-SOE\_V2021-SOE\_FORMAT.csv      |
| hp\_density                     | Harbor\_Porpoise - Fall AMAPPS mapping data from website.csv                                    |
| phyto\_size                     | 1998\_2020-OCCCI-PHYSIZE-STATS-NES\_EPU\_NOESTUARIES-V2021-SOE\_FORMAT.csv                      |
| productivity\_anomaly           | dat\_spec\_rec\_forSOE.Rdata                                                                    |
| productivity\_anomaly           | dat\_spec\_rec\_epu\_forSOE.Rdata                                                               |
| seasonal\_oisst\_anom           | sst.day.mean.ltm.1982-2010.nc                                                                   |
| seasonal\_sst\_anomaly\_gridded | sst.day.mean.2020.nc                                                                            |
| seasonal\_sst\_anomaly\_gridded | sst.day.mean.ltm.1982-2010.nc                                                                   |

**Comment by bbest** [comment]
Hi @superjai, I was able to merge the latest `NOAA-EDAB/ecodata` into `bbest/ecodata` with pull request https://github.com/bbest/ecodata/pull/18, which is the repo used by the Uploader, so you should be able to make changes there. Please first branch `bbest/ecodata` into something like `dataset-attrs4uploader`.

**Comment by bbest** [comment]
The other helpful piece is the spreadsheets which have more info on who (esp emails to work with Uploader) related to which datasets:
* [SOE 2020 Contributors (copy 2020-04-24) - Google Sheets](https://docs.google.com/spreadsheets/d/1ULxD4yIl1Mb189Q6d1iRy0cKdfd_B4XRvz1m4ad52Y4/edit#gid=0)
* [SOE 2021 Contributors - Google Sheets](https://docs.google.com/spreadsheets/d/1i4TCgoyqgDeA6A7pq6oMawhZpQnqegWT6YcyEx82J7o/edit#gid=0)

**Comment by bbest** [comment]
The dataset attribute report [inst/get_dataset_attributes.Rmd](https://github.com/bbest/ecodata/blob/61514778575ca188026c79d9aeed5247885ecdd9/inst/get_dataset_attributes.Rmd) has boolean (TRUE or FALSE) values to indicate:

1. **has_data**: does the dataset load? This is done with `try(get(name), silent = T)` to loop through the datasets, but normally you would simply type the name of the dataset and voila it's lazily available.
2. **has_steward**: does the dataset have the attribute `data_steward`?
3. **has_doc**: does the dataset have the attribute `tech-doc_url`? 
4. **has_files**: does the dataset have the attribute `data_files`?

**Comment by bbest** [comment]
Here's how you can quickly check the given dataset:

```r
# load latest ecodata
devtools::load_all()

# look at attributes of given dataset
attributes(aquaculture)

# source the get_[indicator].R after fixing
source('~/github/ecodata_bbest/data-raw/get_aquaculture.R')

# reload latest ecodata
devtools::load_all()

# relook at attributes of given dataset to check ok
attributes(aquaculture)

# finally re-run the inst/get_dataset_attributes.Rmd to see it move from todo to done
```

**Comment by superjai** [comment]
Hey @bbest - I got as far as I could with fixing the attribute data. Progress made, as you can see [here](https://github.com/bbest/ecodata/blob/dataset-attrs4uploader/inst/get_dataset_attributes.html). However, there were 14 datasets where I ran into trouble. I put my list of problems in a csv file [here](https://github.com/bbest/ecodata/blob/dataset-attrs4uploader/data-raw/problem%20datasets.csv).

**Comment by bbest** [comment]
Datasets that don't need updating in Uploader, so fine to leave as is:
- Shapefiles:
   - `cold_pool_sf`
   - `epu_sf`

**Comment by bbest** [comment]
Here are the R plotting files without a single matching dataset of those valid.

```r
dir_plotR <- glue("{dir_ecodata_src}/chunk-scripts")

plotRs <- tibble(
  plotR = list.files(dir_plotR, "\\.R$")) %>% 
  mutate(
    txt = map_chr(plotR, function(plotR){
      readLines(path(dir_plotR, plotR)) %>% paste(collapse = "\n")}),
    dataset_id = map(txt, function(txt){
      str_match(txt, glue("ecodata::{datasets$dataset_id}"))[,1] %>% 
        na.omit() %>% 
        str_replace("ecodata::", "")}),
    n_datasets = map_int(dataset_id, length))

plotRs %>% 
  filter(n_datasets != 1) %>% 
  mutate(
    dataset_ids = map_chr(dataset_id, paste, collapse = ",")) %>% 
  select(plotR, n_datasets, dataset_ids) %>% 
  kable(format = "markdown")
```

|plotR                                                             | n_datasets|dataset_ids                          |
|:-----------------------------------------------------------------|----------:|:------------------------------------|
|human_dimensions_MAB.Rmd-comdat-comm-revenue.R                    |          2|comdat,hms_landings                  |
|human_dimensions_MAB.Rmd-comdat-total-landings.R                  |          2|comdat,hms_landings                  |
|human_dimensions_MAB.Rmd-commercial-div-species-div.R             |          0|                                     |
|human_dimensions_MAB.Rmd-GIS-setup.R                              |          0|                                     |
|human_dimensions_MAB.Rmd-setup.R                                  |          0|                                     |
|human_dimensions_MAB.Rmd-wind-dev-cumul-MAB.R                     |          0|                                     |
|human_dimensions_MAB.Rmd-wind-dev-cumul.R                         |          0|                                     |
|human_dimensions_MAB.Rmd-wind-dev-NE.R                            |          0|                                     |
|human_dimensions_MAB.Rmd-wind-dev-survey.R                        |          0|                                     |
|human_dimensions_MAB.Rmd-wind-map.R                               |          0|                                     |
|human_dimensions_NE.Rmd-GIS-setup.R                               |          0|                                     |
|human_dimensions_NE.Rmd-hms-landings-comdat-commercial-landings.R |          2|comdat,hms_landings                  |
|human_dimensions_NE.Rmd-ppr_comp90.R                              |          0|                                     |
|human_dimensions_NE.Rmd-ppr_index.R                               |          0|                                     |
|human_dimensions_NE.Rmd-ppr_mtl.R                                 |          0|                                     |
|human_dimensions_NE.Rmd-setup.R                                   |          0|                                     |
|LTL_MAB.Rmd-bottom-temp.R                                         |          2|bottom_temp_glorys,bottom_temp       |
|LTL_MAB.Rmd-gsi.R                                                 |          2|gsi_old,gsi                          |
|LTL_MAB.Rmd-mab-oa.R                                              |          0|                                     |
|LTL_MAB.Rmd-setup.R                                               |          0|                                     |
|LTL_MAB.Rmd-shelf-NERRs-MH-DIN.R                                  |          0|                                     |
|LTL_MAB.Rmd-shelf-NERRs-MP-DIN.R                                  |          0|                                     |
|LTL_NE.Rmd-bottom-temp-glorys.R                                   |          2|bottom_temp_glorys,bottom_temp       |
|LTL_NE.Rmd-chl-pp-anom.R                                          |          2|chl_pp,zoo_sli_anom                  |
|LTL_NE.Rmd-heatwave_image.R                                       |          0|                                     |
|LTL_NE.Rmd-setup.R                                                |          0|                                     |
|macrofauna_MAB.Rmd-aggregate-biomass.R                            |          2|aggregate_biomass,mab_inshore_survey |
|macrofauna_MAB.Rmd-condition-proj.R                               |          0|                                     |
|macrofauna_MAB.Rmd-GIS-setup.R                                    |          0|                                     |
|macrofauna_MAB.Rmd-mab-cf.R                                       |          0|                                     |
|macrofauna_MAB.Rmd-seabird-mab.R                                  |          0|                                     |
|macrofauna_MAB.Rmd-setup.R                                        |          0|                                     |
|macrofauna_NE.Rmd-agg-bio.R                                       |          0|                                     |
|macrofauna_NE.Rmd-gb-cf.R                                         |          0|                                     |
|macrofauna_NE.Rmd-GIS-setup.R                                     |          0|                                     |
|macrofauna_NE.Rmd-gom-cf.R                                        |          0|                                     |
|macrofauna_NE.Rmd-seabird-ne-map.R                                |          0|                                     |
|macrofauna_NE.Rmd-setup.R                                         |          0|

**Comment by bbest** [comment]
Most of the `plotR` files with `n_datasets = 0` are fine since:
- `*setup.R`
- includes images, like `*wind*` and `*ppr*`

For @kimberly-bastille to confirm that these are ok:
- `0`s without `ecodata::` prefix
- `2`s with

Could create separate chunks, eg for `comdat` and `hms_landings`.

## Q: Of the `2`s, which are not covered by other plotR files?

## Q: Where we have multiple matched plotRs, is it obvious how to extract the tab name -- previously presumed a region in filename?

**Comment by bbest** [comment]
## @bbest: How to title tab in plotting step of Uploader?

- strip off: 
  - groups: `human_dimensions_`, `macrofauna_`, `LTL_`
  - `.Rmd`
  - `.R`

human_dimensions_MAB.Rmd-aquaculture.R -> MAB-aquaculture
human_dimensions_NE.Rmd-aquaculture-pieces.R -> NE-aquaculture-pieces

**Comment by bbest** [comment]
More notes: [Data Uploader Debrief - Google Docs](https://docs.google.com/document/d/1sqBMCqNx7fW5EU7KRcLS2QceWzy8aDHTqY437pq7Ljk/edit)
