### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by slucey** [NOAA-EDAB/ecodata#42]
Right now `ecodata` does not have any dependencies only suggestions.  So when I was using `readLines` to pull in code chunks the trend lines were not displaying.  Turns out I did not have the `AICcmodavg` package installed.  While not truly a dependency for the package we should probably list it as a suggested package.  We should revisit dependencies and suggestions for `ecodata`.

**Comment by slucey** [comment]
Correction: `AICcmodavg` is listed under suggestions.

**Comment by kimberly-bastille** [comment]
I just added that after seeing the issue. Let me know if you come across anything else that I should address.

**Comment by andybeet** [comment]
@kimberly-bastille Sean H had started to pull the analysis out of ecodata and into [ecotrend](https://github.com/NOAA-EDAB/ecotrend) to leave ecodata as just a data package. Then `ecotrend` would house the analysis for the SOE stuff. Maybe that should be continued. I also see that `nmle`, `grid`,`magrittr` are used in the package but not listed in DESCRIPTIONS.

I would suggest as a quick fix that these functions (plus a few others) should be listed as Imports and not suggests until the code is moved out of ecodata

The others listed in suggests must be packages used in the `data-raw` folder.

**Comment by slucey** [comment]
> 
> 
> I just added that after seeing the issue. Let me know if you come across anything else that I should address.

Oh good...thought I was losing it when Andy mentioned it was in there.
