### ISSUE TITLE
Repo releases and links in readme

### ISSUE THREAD

**Issue by kimberly-bastille** [NOAA-EDAB/ecodata#50]
Add tags and release the SOE repos:
- [x] ecodata
- [x] SOE NEFMC
- [x] SOE MAFMC
- [x] Tech Doc 
- [x] Catalog

Update link tables in readme:
- [ ] ecodata
- [ ] SOE NEFMC
- [ ] SOE MAFMC
- [ ] Tech Doc 
- [ ] Catalog

Sorry, I wasn't able to complete this before my last day.

Note: Brandon (BBeltz1) is completing these and updating the checklist above.

**Comment by BBeltz1** [comment]
Created initial pre-release of catalog repository in anticipation of upcoming changes.
