### ISSUE TITLE
reorganize visualizations

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/ecodata#56]
Rework visualization Rmds to have fewer figures (in more Rmds) to streamline updates.

Maintain visualization Rmds and code chunks within ecodata but do not post them here.

Instead, catalog will have all indicator visualizations using current code chunk or new figure function workflow.

**Comment by sgaichas** [comment]
Update: @andybeet has piloted a figure function workflow. We will use this for 2024.

Steps to implement workflow:

- [ ] Consolidate current setup chunks into a single setup function with plot defaults
- [ ] Build plot_[dataset_name] function template that has 2 steps
    - [ ] First calls the setup function to populate plot defaullts
    - [ ] Then calls existing plot code from the chunk_scripts
    - [ ]  Has standardized documentation at the top

**Comment by sgaichas** [comment]
Once Sarah completes the above template, @BBeltz1 has the fun to copy all current chunk scripts into new function files. These functions will be used in catalog  chapters and all other products.

**Comment by andybeet** [comment]
ecodata branch [`andy_ plotfns`](https://github.com/NOAA-EDAB/ecodata/tree/andy_plotfns) updated to include `plot_forage_index`. 
`dev` branch has also been pulled into `andy_plotfns`

**Comment by sgaichas** [comment]
added `plot_setup` to andy_plotfns branch and modified  `plot_forage_index` to call it in cc03ffaf470c40e29645891a5f3ed3c5fc785926 and updated documentation c95f15e2edf8ab037ce1234210aba32d2ca04aa8 and 490c1c63637c143e6ccede8b33d09a55c7556cc2

**Comment by andybeet** [comment]
This looks good. All works well
I did remove the `library` statement (in `plot_setup`) and replaced with the `st_as_sf` function.

**Comment by sgaichas** [comment]
thanks for fixing the `sf` issue. a general plot function template was added in 317fd4f29609376db23720551a128201d6f0ad7d
