### ISSUE TITLE
check release/versioning in ecodata

### ISSUE THREAD

**Issue by BBeltz1** [NOAA-EDAB/ecodata#69]

**Comment by andybeet** [comment]
@BBeltz1 Since the versioning was the last thing you did, (linked to the most recent commit) i wonder if we can delete the release, change DESCRIPTION to v4.0.0, then re-release

**Comment by BBeltz1** [comment]
@andybeet seems reasonable to me. Releasing was quick and easy, so shouldn't be a problem.

**Comment by andybeet** [comment]
ok, but lets fix the gridded data issue first.
