### ISSUE TITLE
Time series length for commercial landings and revenue

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/ecodata#73]
`ecodata::comdat` and `ecodata::bennet` both have years from 1960 or 1964

In the SOE we plot from the mid-80's on

Value data in StockEff is not included prior to 1981 due to concerns with data quality but we have included it in comlandr

Need to reconcile which years' data to include in ecodata (not report data that may be incorrect) and which to plot

**Comment by andybeet** [comment]
We will plot data from 1982+. 
 "did not include WOLAN because there were concerns as to the validity of the data. We have no way of validating it and had heard a few years ago that this field was not populated properly in this series of objects." PopDy correspondence
