### ISSUE TITLE
Write to ERDDAP server via R

### ISSUE THREAD

**Issue by slarge** [NOAA-EDAB/ecodata#8]

**Comment by slarge** [comment]
Not sure if this is a requirement for the package... maybe we just need to create a workflow for how to move data from `ecodata` to ERDDAP after `ecodata` is versioned (with DOI, etc).

**Comment by andybeet** [comment]
agreed. not sure this functionality should be in this package.

**Comment by seanhardison1** [comment]
I think you're right that developing a workflow is the better option. It turns out that getting the files onto the server is the easy part (using the package `ssh`). The real issue is generating the XML through ERDDAP, which is necessary to make the data accessible.  I will work on this
