### ISSUE TITLE
ecodata::ch_bay_sal data error?

### ISSUE THREAD

**Issue by andybeet** [NOAA-EDAB/ecodata#90]
`ecodata::ch_bay_sal ` data set has a spurious entry

![image](https://github.com/NOAA-EDAB/ecodata/assets/22455149/e708aedf-7906-48a9-9f64-dc9a4fee6e39)
![image](https://github.com/NOAA-EDAB/ecodata/assets/22455149/bf6a3af2-57ad-4d0d-9b38-60642c4c1b01)

**Comment by sgaichas** [comment]
thanks @andybeet! @BBeltz1 can you please contact the contributor for a correction?

**Comment by sgaichas** [comment]
@andybeet looks like I may have hardcoded the year in the plot function legend label

**Comment by BBeltz1** [comment]
@andybeet @sgaichas i'm reaching out to the contributor for the correction.

**Comment by andybeet** [comment]
fixed!
